# Generated by Django 5.2.16 on 2026-07-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontext',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
