# Generated by Django 5.2.16 on 2026-08-01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_usercontext_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pet_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models._user_pet_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pet_name",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="user",
            name="show_pet",
            field=models.BooleanField(default=False),
        ),
    ]
