# Generated by Django 5.2.16 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_pet"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pet_preset",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fox", "Fox"),
                    ("cat", "Cat"),
                    ("robot", "Robot"),
                    ("dragon", "Dragon"),
                    ("rabbit", "Rabbit"),
                    ("blob", "Blob"),
                ],
                default="",
                max_length=12,
            ),
        ),
    ]
