# Generated by Django 5.2.16 on 2026-07-27 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('input_schema', models.JSONField()),
                ('system_instructions', models.TextField()),
                ('workflow_steps', models.JSONField()),
                ('model_policy', models.JSONField(blank=True, default=dict)),
                ('tool_policy', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField()),
                ('eval_set', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_version', models.PositiveIntegerField()),
                ('input_payload', models.JSONField()),
                ('idempotency_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ok', 'OK'), ('error', 'Error'), ('insufficient_credits', 'Insufficient credits'), ('blocked', 'Blocked by moderation')], default='pending', max_length=24)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, null=True)),
                ('credits_charged', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'agent', 'idempotency_key')},
            },
        ),
    ]
