# Generated by Django 5.2.16 on 2026-08-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentrun_preferred_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='category',
            field=models.CharField(choices=[('content', 'Контент'), ('research', 'Исследования'), ('documents', 'Документы'), ('finance', 'Финансы')], max_length=32),
        ),
    ]
