# Generated by Django 5.2.16 on 2026-08-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0034_seed_product_demo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='category',
            field=models.CharField(choices=[('content', 'Контент'), ('research', 'Исследования'), ('documents', 'Документы'), ('finance', 'Финансы'), ('code', 'Код'), ('video', 'Видео')], max_length=32),
        ),
    ]
