# Generated by Django 5.2.16 on 2026-08-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0036_split_code_and_video_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='category',
            field=models.CharField(choices=[('content', 'Контент'), ('research', 'Исследования'), ('documents', 'Документы'), ('finance', 'Финансы'), ('code', 'Код'), ('video', 'Видео'), ('audio', 'Аудио')], max_length=32),
        ),
    ]
