# Generated by Django 5.0.9 on 2026-07-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0004_add_media_ops_resources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unlockableresource",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text_task", "Text task"),
                    ("image_task", "Image task"),
                    ("media_task", "Media task (voice/OCR)"),
                ],
                max_length=16,
            ),
        ),
    ]
