# Generated by Django 5.0.9 on 2026-07-20 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0007_add_photo_analysis_resource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelUnlockable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=32)),
                ("provider", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=64)),
                ("min_requests", models.PositiveIntegerField()),
                ("min_distinct_days", models.PositiveIntegerField()),
                ("sort_order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["task", "sort_order"],
                "unique_together": {("task", "provider", "model")},
            },
        ),
        migrations.CreateModel(
            name="UserModelUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="progression.modelunlockable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_unlocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "resource")},
            },
        ),
    ]
