# Generated by Django 5.2.16 on 2026-07-31 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=32)),
                ('version', models.CharField(blank=True, default='', max_length=32)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ok', 'OK'), ('error', 'Error'), ('insufficient_credits', 'Insufficient credits'), ('task_locked', 'Task locked (free tier)'), ('blocked', 'Blocked by moderation')], default='pending', max_length=24)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('credits_charged', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('mocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
