# Generated by Django 5.0.9 on 2026-07-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="reason",
            field=models.CharField(
                choices=[
                    ("signup_bonus", "Signup bonus"),
                    ("topup", "Top-up"),
                    ("chat_request", "Chat request"),
                    ("image_request", "Image request"),
                    ("transcription_request", "Voice transcription request"),
                    ("speech_request", "Text-to-speech request"),
                    ("document_request", "Document extraction request"),
                    ("refund", "Refund"),
                ],
                max_length=32,
            ),
        ),
    ]
