# Generated by Django 5.0.9 on 2026-07-19 22:23

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_ledgerentry_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("topup", "Top-up"),
                    ("subscription", "Subscription"),
                ],
                default="topup",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="credits_amount",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yookassa_payment_method_id",
                    models.CharField(max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "price_rub",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("current_period_end", models.DateTimeField()),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
