# Generated by Django 5.0.9 on 2026-07-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_payment_kind_alter_payment_credits_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="reason",
            field=models.CharField(
                choices=[
                    ("signup_bonus", "Signup bonus"),
                    ("topup", "Top-up"),
                    ("chat_request", "Chat request"),
                    ("image_request", "Image request"),
                    ("transcription_request", "Voice transcription request"),
                    ("speech_request", "Text-to-speech request"),
                    ("document_request", "Document extraction request"),
                    ("photo_analysis_request", "Photo analysis request"),
                    ("refund", "Refund"),
                    ("referral_bonus", "Referral bonus"),
                ],
                max_length=32,
            ),
        ),
    ]
