# Generated by Django 5.0.9 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_ledgerentry_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("non_renewing", "Non-renewing"),
                    ("past_due", "Past due"),
                    ("canceled", "Canceled"),
                ],
                default="active",
                max_length=16,
            ),
        ),
    ]
