# Generated by Django 5.0.9 on 2026-07-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='reason',
            field=models.CharField(choices=[('signup_bonus', 'Signup bonus'), ('topup', 'Top-up'), ('chat_request', 'Chat request'), ('image_request', 'Image request'), ('transcription_request', 'Voice transcription request'), ('speech_request', 'Text-to-speech request'), ('document_request', 'Document extraction request'), ('photo_analysis_request', 'Photo analysis request'), ('live_voice_session', 'Live voice session'), ('refund', 'Refund'), ('referral_bonus', 'Referral bonus')], max_length=32),
        ),
    ]
