# Generated by Django 5.2.16 on 2026-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_ledgerentry_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='reason',
            field=models.CharField(choices=[('signup_bonus', 'Signup bonus'), ('topup', 'Top-up'), ('chat_request', 'Chat request'), ('image_request', 'Image request'), ('transcription_request', 'Voice transcription request'), ('speech_request', 'Text-to-speech request'), ('document_request', 'Document extraction request'), ('photo_analysis_request', 'Photo analysis request'), ('live_voice_session', 'Live voice session'), ('knowledge_ingest_request', 'Knowledge ingest request'), ('refund', 'Refund'), ('referral_bonus', 'Referral bonus')], max_length=32),
        ),
    ]
