# Generated by Django 5.0.9 on 2026-07-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='used_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
