# Generated by Django 5.0.9 on 2026-07-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_requestlog_used_fallback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('insufficient_credits', 'Insufficient credits'), ('blocked', 'Blocked by moderation')], default='ok', max_length=24),
        ),
    ]
