# Generated by Django 5.2.16 on 2026-08-03 10:23

import django.db.models.deletion
import knowledge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(default=knowledge.models._generate_public_key, editable=False, max_length=40, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_widgets', to='knowledge.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
