# Generated by Django 5.0.9 on 2026-07-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagegen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="telegram_chat_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
