# Generated by Django 5.0.9 on 2026-07-19 14:45

from django.db import migrations, models

import imagegen.models


class Migration(migrations.Migration):

    dependencies = [
        ("imagegen", "0002_generatedimage_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="source_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=imagegen.models._upload_to
            ),
        ),
    ]
