# Generated by Django 5.2.16 on 2026-08-03 03:55

import django.db.models.deletion
import docgen.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(max_length=4000)),
                ('file', models.FileField(blank=True, null=True, upload_to=docgen.models._upload_to_pptx)),
                ('status', models.CharField(choices=[('ok', 'OK')], default='ok', max_length=24)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('credits_charged', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedSpreadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(max_length=4000)),
                ('file', models.FileField(blank=True, null=True, upload_to=docgen.models._upload_to_excel)),
                ('status', models.CharField(choices=[('ok', 'OK')], default='ok', max_length=24)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('credits_charged', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_spreadsheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
