# Generated by Django 5.0.9 on 2026-07-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0004_rename_mode_requestlog_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("error", "Error"),
                    ("insufficient_credits", "Insufficient credits"),
                    ("blocked", "Blocked by moderation"),
                    ("task_locked", "Task locked (free tier)"),
                ],
                default="ok",
                max_length=24,
            ),
        ),
    ]
