# Generated by Django 5.0.9 on 2026-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_thread_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='task',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
