# Generated by Django 5.2.16 on 2026-07-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
