# Generated by Django 5.2.16 on 2026-07-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_alter_preset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='active_generation_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
