# Generated by Django 5.0.9 on 2026-07-17 22:28

import django.db.models.deletion
import imagegen.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(max_length=4000)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ok', 'OK'), ('error', 'Error'), ('insufficient_credits', 'Insufficient credits'), ('blocked', 'Blocked by moderation')], default='pending', max_length=24)),
                ('image', models.ImageField(blank=True, null=True, upload_to=imagegen.models._upload_to)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('credits_charged', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('mocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
