# Generated by Django 5.0.9 on 2026-07-20 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import media_ops.models


class Migration(migrations.Migration):

    dependencies = [
        ("media_ops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=media_ops.models._upload_to_photo
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                (
                    "provider",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("insufficient_credits", "Insufficient credits"),
                            ("task_locked", "Task locked (free tier)"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=0, max_digits=10
                    ),
                ),
                (
                    "credits_charged",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("mocked", models.BooleanField(default=False)),
                (
                    "telegram_chat_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
