# Generated by Django 5.0.9 on 2026-07-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_ops", "0002_photoanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentextraction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ok", "OK"),
                    ("error", "Error"),
                    ("insufficient_credits", "Insufficient credits"),
                    ("task_locked", "Task locked (free tier)"),
                    ("blocked", "Blocked by moderation"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="photoanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ok", "OK"),
                    ("error", "Error"),
                    ("insufficient_credits", "Insufficient credits"),
                    ("task_locked", "Task locked (free tier)"),
                    ("blocked", "Blocked by moderation"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="speechclip",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ok", "OK"),
                    ("error", "Error"),
                    ("insufficient_credits", "Insufficient credits"),
                    ("task_locked", "Task locked (free tier)"),
                    ("blocked", "Blocked by moderation"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ok", "OK"),
                    ("error", "Error"),
                    ("insufficient_credits", "Insufficient credits"),
                    ("task_locked", "Task locked (free tier)"),
                    ("blocked", "Blocked by moderation"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
    ]
