# Generated by Django 5.0.9 on 2026-07-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarginDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Margin dashboard",
                "verbose_name_plural": "Margin dashboard",
                "managed": False,
            },
        ),
    ]
